package com.manishjavadev.service.accounts;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2018-02-18T17:32:48.194+05:30
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "Accounts", 
                  wsdlLocation = "file:/C:/Users/Manish/git/webservice/soap/jax-ws-apache-cxf-account-service/jax-ws-apache-cxf-account-service-demo/src/main/resources/wsdl/Accounts.wsdl",
                  targetNamespace = "http://www.manishjavadev.com/service/Accounts/") 
public class Accounts_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.manishjavadev.com/service/Accounts/", "Accounts");
    public final static QName AccountsSOAP = new QName("http://www.manishjavadev.com/service/Accounts/", "AccountsSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Manish/git/webservice/soap/jax-ws-apache-cxf-account-service/jax-ws-apache-cxf-account-service-demo/src/main/resources/wsdl/Accounts.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Accounts_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Manish/git/webservice/soap/jax-ws-apache-cxf-account-service/jax-ws-apache-cxf-account-service-demo/src/main/resources/wsdl/Accounts.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Accounts_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Accounts_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Accounts_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Accounts_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Accounts_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Accounts_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Accounts
     */
    @WebEndpoint(name = "AccountsSOAP")
    public Accounts getAccountsSOAP() {
        return super.getPort(AccountsSOAP, Accounts.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Accounts
     */
    @WebEndpoint(name = "AccountsSOAP")
    public Accounts getAccountsSOAP(WebServiceFeature... features) {
        return super.getPort(AccountsSOAP, Accounts.class, features);
    }

}
